// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zenny_Api.Data;

#nullable disable

namespace Zenny_Api.Migrations
{
    [DbContext(typeof(MovementDbContext))]
    [Migration("20240918175406_MovementsSeeders")]
    partial class MovementsSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zenny_Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category1")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("category");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Category1" }, "category_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Zenny_Api.Models.Movement", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<int>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("categories_id")
                        .HasDefaultValueSql("'9'");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("movement_date");

                    b.Property<int>("TransactionTypesId")
                        .HasColumnType("int(11)")
                        .HasColumnName("transaction_types_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoriesId" }, "categories_id");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE1");

                    b.HasIndex(new[] { "TransactionTypesId" }, "transaction_types_id");

                    b.ToTable("movements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 1,
                            Value = 10000.0
                        },
                        new
                        {
                            Id = 2u,
                            CategoriesId = 1,
                            MovementDate = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 1,
                            Value = 5000.0
                        },
                        new
                        {
                            Id = 3u,
                            CategoriesId = 2,
                            MovementDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 1,
                            Value = 2000.0
                        },
                        new
                        {
                            Id = 4u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 2,
                            Value = 15000.0
                        },
                        new
                        {
                            Id = 5u,
                            CategoriesId = 4,
                            MovementDate = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 2,
                            Value = 7000.0
                        },
                        new
                        {
                            Id = 6u,
                            CategoriesId = 5,
                            MovementDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 2,
                            Value = 3000.0
                        },
                        new
                        {
                            Id = 7u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 3,
                            Value = 25000.0
                        },
                        new
                        {
                            Id = 8u,
                            CategoriesId = 3,
                            MovementDate = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 3,
                            Value = 12000.0
                        },
                        new
                        {
                            Id = 9u,
                            CategoriesId = 6,
                            MovementDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 3,
                            Value = 5000.0
                        },
                        new
                        {
                            Id = 10u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 3,
                            Value = 20000.0
                        },
                        new
                        {
                            Id = 11u,
                            CategoriesId = 7,
                            MovementDate = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 3,
                            Value = 10000.0
                        },
                        new
                        {
                            Id = 12u,
                            CategoriesId = 8,
                            MovementDate = new DateTime(2024, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 3,
                            Value = 4000.0
                        },
                        new
                        {
                            Id = 13u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 4,
                            Value = 35000.0
                        },
                        new
                        {
                            Id = 14u,
                            CategoriesId = 9,
                            MovementDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 4,
                            Value = 18000.0
                        },
                        new
                        {
                            Id = 15u,
                            CategoriesId = 10,
                            MovementDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 4,
                            Value = 6000.0
                        },
                        new
                        {
                            Id = 16u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 4,
                            Value = 22000.0
                        },
                        new
                        {
                            Id = 17u,
                            CategoriesId = 11,
                            MovementDate = new DateTime(2024, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 4,
                            Value = 15000.0
                        },
                        new
                        {
                            Id = 18u,
                            CategoriesId = 12,
                            MovementDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 4,
                            Value = 5000.0
                        },
                        new
                        {
                            Id = 19u,
                            CategoriesId = 0,
                            MovementDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 1,
                            UserId = 5,
                            Value = 40000.0
                        },
                        new
                        {
                            Id = 20u,
                            CategoriesId = 13,
                            MovementDate = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionTypesId = 2,
                            UserId = 5,
                            Value = 25000.0
                        });
                });

            modelBuilder.Entity("Zenny_Api.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TransactionType1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE2");

                    b.HasIndex(new[] { "TransactionType1" }, "transaction_type_UNIQUE")
                        .IsUnique();

                    b.ToTable("transaction_types", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
