// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zenny_Api.Data;

#nullable disable

namespace Zenny_Api.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20240919180134_UserSeeders")]
    partial class UserSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zenny_Api.Models.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubscriptionType1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subscription_type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "SubscriptionType1" }, "subscription_type_UNIQUE")
                        .IsUnique();

                    b.ToTable("subscription_types", (string)null);
                });

            modelBuilder.Entity("Zenny_Api.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11) unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int?>("SubscriptionTypesId")
                        .HasColumnType("int(11)")
                        .HasColumnName("subscription_types_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "SubscriptionTypesId" }, "subscription_types_id");

                    b.HasIndex(new[] { "Id" }, "users_UNIQUE")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Email = "john.doe@gmail.com",
                            LastName = "Doe",
                            Name = "John",
                            Password = "AQAAAAIAAYagAAAAEMdFhcD1F5/AEIUpec2VvWSdPRIoL1XQhv3ZUD1vLeOPjH5Hd9ttkWii7vYBDbIAOg==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 2u,
                            Email = "jane.smith@gmail.com",
                            LastName = "Smith",
                            Name = "Jane",
                            Password = "AQAAAAIAAYagAAAAEOL51N9ITma/uetBXtmwTKwB1jYW2gh1Lu+7IoUn10LDiZLjLeP9cmYD9mX4X6l//A==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 3u,
                            Email = "Jhonh@gmail.com",
                            LastName = "gency",
                            Name = "John",
                            Password = "AQAAAAIAAYagAAAAEMy9Y8UXBvAToeGTkAESFaQ/+BOQyfh9PvKUtcLY5F3ux0UwzxIJguH/yCJMdPgs5Q==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 4u,
                            Email = "david.williams@gmail.com",
                            LastName = "Williams",
                            Name = "David",
                            Password = "AQAAAAIAAYagAAAAEMwLpIDa/KH8lpkhv+GoRPyUanbnKOVkWTqFCyOEtgRRFDDlXIm5wAjbxEjpSArWtA==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 5u,
                            Email = "sophia.davis@gmail.com",
                            LastName = "Davis",
                            Name = "Sophia",
                            Password = "AQAAAAIAAYagAAAAECA8MhaHudUaw8vPoZzVNieeQ5+IL4WxitfJKupeZcEo5ETbvyilMLw/wSdIXaKBkg==",
                            SubscriptionTypesId = 2
                        },
                        new
                        {
                            Id = 6u,
                            Email = "james.miller@hotmail.com",
                            LastName = "Miller",
                            Name = "James",
                            Password = "AQAAAAIAAYagAAAAEIEN9uyCQUtm/qaVh/TFA/K2debhdvlNMKkWtgM3lQROQZyap9u/KqKcH+yUqhZE+w==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 7u,
                            Email = "isabella.garcia@hotmail.com",
                            LastName = "Garcia",
                            Name = "Isabella",
                            Password = "AQAAAAIAAYagAAAAEO0qlrHwwg3pDj6pCoIrxgqX0kORKx8Bfzsdsi6/QRXOb9HrvtGz/TZ/6UpRi4cOig==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 8u,
                            Email = "emma.rodriguez@hotmail.com",
                            LastName = "Rodriguez",
                            Name = "Emma",
                            Password = "AQAAAAIAAYagAAAAEO0qlrHwwg3pDj6pCoIrxgqX0kORKx8Bfzsdsi6/QRXOb9HrvtGz/TZ/6UpRi4cOig==",
                            SubscriptionTypesId = 2
                        },
                        new
                        {
                            Id = 9u,
                            Email = "olivia.wilson@hotmail.com",
                            LastName = "Wilson",
                            Name = "Olivia",
                            Password = "AQAAAAIAAYagAAAAENNiUrRyyMsKBHWjGJkxcaggGlz/w55oHx+JeoBE91Vq8ufWIElWX3S0cz9gfbPT4A==",
                            SubscriptionTypesId = 1
                        },
                        new
                        {
                            Id = 10u,
                            Email = "ava.anderson@hotmail.com",
                            LastName = "Anderson",
                            Name = "Ava",
                            Password = "AQAAAAIAAYagAAAAENNiUrRyyMsKBHWjGJkxcaggGlz/w55oHx+JeoBE91Vq8ufWIElWX3S0cz9gfbPT4A==",
                            SubscriptionTypesId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
